alter session set current_schema = PROGTIRDB; --xafnem-vujpoq-vupNu7

CREATE TABLE CLIENTI (
ID NUMBER NOT NULL,
NOME VARCHAR(50) NOT NULL,
P_IVA VARCHAR(12) NOT NULL UNIQUE,
TELEFONO VARCHAR(30),
PRIMARY KEY (ID)
);

